tasks:
  - name: Setup & Run Cooja with Simulation
    init: |
      sudo apt update
      sudo apt install -y ant openjdk-8-jdk git
      git clone --recursive https://github.com/contiki-ng/contiki-ng.git
    command: |
      cd contiki-ng/tools/cooja
      ant run -Dargs="/workspace/border-intrusion-wsn/border_security.csc" &

vscode:
  extensions:
    - ms-vscode.simple-browser

ports:
  - port: 8080
    onOpen: open-browser
  - port: 5900
    onOpen: notify
