# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Clone Contiki-NG if not already present
      if [ ! -d contiki-ng ]; then
        git clone --depth 1 https://github.com/contiki-ng/contiki-ng.git
      fi
      cd contiki-ng/tools/cooja
      ./gradlew assemble || true
  - command: |
      cd contiki-ng/tools/cooja
      ./gradlew run &
      sleep 8
      gp preview http://localhost:6080

ports:
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.cpptools
